Dans-Plugins/Medieval-Roleplay-Engine

src/main/java/rpsystem/Commands/WhisperCommand.java, src/main/java/rpsystem/Utilities.java
=> players are now informed of how many players heard them when they whisper something

src/main/java/rpsystem/EventHandlers/AsyncPlayerChatEventHandler.java, src/main/java/rpsystem/EventHandlers/PlayerInteractAtEntityEventHandler.java, src/main/java/rpsystem/EventHandlers/PlayerJoinEventHandler.java, src/main/java/rpsystem/EventRegistry.java, src/main/java/rpsystem/MedievalRoleplayEngine.java
=> created EventRegistry.java

src/main/java/rpsystem/CommandInterpreter.java, src/main/java/rpsystem/EventHandlers/PlayerJoinEventHandler.java, src/main/java/rpsystem/MedievalRoleplayEngine.java, src/main/java/rpsystem/StorageManager.java, src/main/java/rpsystem/Utilities.java, src/main/java/rpsystem/data/PersistentData.java
=> created PersistentData.java

pom.xml, src/main/java/rpsystem/ColorChecker.java, src/main/java/rpsystem/CommandInterpreter.java, src/main/java/rpsystem/Commands/CardCommand.java, src/main/java/rpsystem/Commands/ConfigCommand.java, src/main/java/rpsystem/Commands/HelpCommand.java, src/main/java/rpsystem/Commands/WhisperCommand.java, src/main/java/rpsystem/Commands/YellCommand.java, src/main/java/rpsystem/ConfigManager.java, src/main/java/rpsystem/EventHandlers/AsyncPlayerChatEventHandler.java, src/main/java/rpsystem/MedievalRoleplayEngine.java, src/main/resources/plugin.yml
closes #118 
closes #165 
closes #166 
closes #168 
closes #169 
closes #167
=> Configuration

pom.xml, src/main/java/dansplugins/rpsystem/ColorChecker.java, src/main/java/dansplugins/rpsystem/CommandInterpreter.java, src/main/java/dansplugins/rpsystem/Commands/BirdCommand.java, src/main/java/dansplugins/rpsystem/Commands/CardCommand.java, src/main/java/dansplugins/rpsystem/Commands/ConfigCommand.java, src/main/java/dansplugins/rpsystem/Commands/HelpCommand.java, src/main/java/dansplugins/rpsystem/Commands/RollCommand.java, src/main/java/dansplugins/rpsystem/Commands/TitleCommand.java, src/main/java/dansplugins/rpsystem/Commands/WhisperCommand.java, src/main/java/dansplugins/rpsystem/Commands/YellCommand.java, src/main/java/dansplugins/rpsystem/ConfigManager.java, src/main/java/dansplugins/rpsystem/EventHandlers/AsyncPlayerChatEventHandler.java, src/main/java/dansplugins/rpsystem/EventHandlers/PlayerInteractAtEntityEventHandler.java, src/main/java/dansplugins/rpsystem/EventHandlers/PlayerJoinEventHandler.java, src/main/java/dansplugins/rpsystem/EventRegistry.java, src/main/java/dansplugins/rpsystem/MedievalRoleplayEngine.java, src/main/java/dansplugins/rpsystem/Objects/CharacterCard.java, src/main/java/dansplugins/rpsystem/StorageManager.java, src/main/java/dansplugins/rpsystem/Utilities.java, src/main/java/dansplugins/rpsystem/bStats/Metrics.java, src/main/java/dansplugins/rpsystem/data/PersistentData.java, src/main/resources/plugin.yml, src/test/java/dansplugins/rpsystem/Commands/RollCommandTest.java
=> Permissions

src/main/java/dansplugins/rpsystem/CommandInterpreter.java, src/main/java/dansplugins/rpsystem/Commands/BirdCommand.java, src/main/java/dansplugins/rpsystem/Commands/WhisperCommand.java, src/main/java/dansplugins/rpsystem/Commands/YellCommand.java, src/main/java/dansplugins/rpsystem/EventHandlers/AsyncPlayerChatEventHandler.java, src/main/java/dansplugins/rpsystem/Utilities.java
=> nearby players are now informed when a bird delivers a message

src/main/java/dansplugins/rpsystem/CommandInterpreter.java, src/main/java/dansplugins/rpsystem/Commands/BirdCommand.java, src/main/java/dansplugins/rpsystem/Commands/CardCommand.java, src/main/java/dansplugins/rpsystem/EventHandlers/AsyncPlayerChatEventHandler.java, src/main/java/dansplugins/rpsystem/EventHandlers/PlayerInteractAtEntityEventHandler.java, src/main/java/dansplugins/rpsystem/MedievalRoleplayEngine.java, src/main/java/dansplugins/rpsystem/data/EphemeralData.java
=> created EphemeralData.java

src/main/java/dansplugins/rpsystem/Commands/ConfigCommand.java, src/main/java/dansplugins/rpsystem/ConfigManager.java, src/main/java/dansplugins/rpsystem/MedievalRoleplayEngine.java
=> the config will now only be overwritten if it is altered in-game

src/main/java/dansplugins/rpsystem/CommandInterpreter.java, src/main/java/dansplugins/rpsystem/commands/CardCommand.java, src/main/java/dansplugins/rpsystem/commands/EmoteCommand.java, src/main/java/dansplugins/rpsystem/commands/GlobalChatCommand.java, src/main/java/dansplugins/rpsystem/commands/LocalChatCommand.java, src/main/java/dansplugins/rpsystem/commands/NewRollCommand.java, src/main/java/dansplugins/rpsystem/commands/RollCommand.java, src/test/java/dansplugins/rpsystem/commands/RollCommandTest.java
=> Moving code for commands into command classes

src/main/java/dansplugins/rpsystem/CommandInterpreter.java, src/main/java/dansplugins/rpsystem/ConfigManager.java, src/main/java/dansplugins/rpsystem/MedievalRoleplayEngine.java, src/main/java/dansplugins/rpsystem/Messenger.java, src/main/java/dansplugins/rpsystem/commands/BirdCommand.java, src/main/java/dansplugins/rpsystem/commands/EmoteCommand.java, src/main/java/dansplugins/rpsystem/commands/LocalOOCChatCommand.java, src/main/java/dansplugins/rpsystem/commands/RollCommand.java, src/main/java/dansplugins/rpsystem/commands/WhisperCommand.java, src/main/java/dansplugins/rpsystem/commands/YellCommand.java, src/main/java/dansplugins/rpsystem/data/EphemeralData.java, src/main/java/dansplugins/rpsystem/eventhandlers/AsyncPlayerChatEventHandler.java, src/main/resources/plugin.yml
closes #172 
closes #193 
closes #194 
closes #195
=> Local OOC Chat

src/main/java/dansplugins/rpsystem/commands/HelpCommand.java
=> help command now only shows /rp and /ooc as chat commands

.idea/misc.xml, src/main/java/dansplugins/rpsystem/ConfigManager.java
=> changed default emote color to yellow

pom.xml, src/main/java/dansplugins/rpsystem/MedievalRoleplayEngine.java, src/main/java/dansplugins/rpsystem/placeholders/PlaceholderAPI.java, src/main/resources/plugin.yml
@philbgarner is responsible for this improvement.
Added Placeholder Tokens:
- card_name
- card_age
- card_race
- card_subculture
- card_gender
- card_religion
closes #217
=> PlaceholderAPI Integration w/ 6 initial placeholder tokens

.idea/misc.xml, pom.xml, src/main/java/dansplugins/rpsystem/MedievalRoleplayEngine.java, src/main/java/dansplugins/rpsystem/eventhandlers/AsyncPlayerChatEventHandler.java, src/main/resources/plugin.yml
This is currently a work in progress. More of the implementation will need to be completed and testing will be necessary before this can be merged.
=> anything between two astericks in local chat will now be printed afterwards as an emote

pom.xml, src/main/java/dansplugins/rpsystem/MedievalRoleplayEngine.java, src/main/java/dansplugins/rpsystem/eventhandlers/AsyncPlayerChatEventHandler.java, src/main/resources/plugin.yml
=> Fixed null error and empty RP message bug

.idea/misc.xml, pom.xml, src/main/java/dansplugins/rpsystem/CommandInterpreter.java, src/main/java/dansplugins/rpsystem/MedievalFactionsIntegrator.java, src/main/java/dansplugins/rpsystem/commands/BirdCommand.java, src/main/java/dansplugins/rpsystem/commands/GlobalChatCommand.java, src/main/java/dansplugins/rpsystem/commands/LocalChatCommand.java, src/main/java/dansplugins/rpsystem/commands/WhisperCommand.java, src/main/java/dansplugins/rpsystem/eventhandlers/AsyncPlayerChatEventHandler.java, src/main/resources/plugin.yml
If Medieval Factions is installed, players will be removed from faction chat when they enter local or global chat.
closes #209
=> Medieval Factions Integration

pom.xml, src/main/java/dansplugins/rpsystem/ConfigManager.java, src/main/java/dansplugins/rpsystem/MedievalFactionsIntegrator.java, src/main/java/dansplugins/rpsystem/MedievalRoleplayEngine.java, src/main/java/dansplugins/rpsystem/commands/BirdCommand.java, src/main/java/dansplugins/rpsystem/commands/CardCommand.java, src/main/java/dansplugins/rpsystem/commands/ConfigCommand.java, src/main/java/dansplugins/rpsystem/commands/EmoteCommand.java, src/main/java/dansplugins/rpsystem/commands/GlobalChatCommand.java, src/main/java/dansplugins/rpsystem/commands/HelpCommand.java, src/main/java/dansplugins/rpsystem/commands/LocalChatCommand.java, src/main/java/dansplugins/rpsystem/commands/LocalOOCChatCommand.java, src/main/java/dansplugins/rpsystem/commands/NewRollCommand.java, src/main/java/dansplugins/rpsystem/commands/RollCommand.java, src/main/java/dansplugins/rpsystem/commands/TitleCommand.java, src/main/java/dansplugins/rpsystem/commands/WhisperCommand.java, src/main/java/dansplugins/rpsystem/commands/YellCommand.java, src/main/java/dansplugins/rpsystem/eventhandlers/PlayerInteractAtEntityEventHandler.java, src/main/java/dansplugins/rpsystem/utils/ColorChecker.java, src/main/resources/plugin.yml, src/test/java/dansplugins/rpsystem/commands/RollCommandTest.java
Added 3 new config options.
closes #177
closes #178
closes #179
=> Alert Colors

src/main/java/dansplugins/rpsystem/CommandInterpreter.java, src/main/java/dansplugins/rpsystem/ConfigManager.java, src/main/java/dansplugins/rpsystem/MedievalFactionsIntegrator.java, src/main/java/dansplugins/rpsystem/commands/HelpCommand.java, src/main/java/dansplugins/rpsystem/commands/LocalChatCommand.java, src/main/java/dansplugins/rpsystem/eventhandlers/AsyncPlayerChatEventHandler.java
=> Toggleable Chat Features

src/main/java/dansplugins/rpsystem/MedievalFactionsIntegrator.java, src/main/java/dansplugins/rpsystem/MedievalRoleplayEngine.java, src/main/java/dansplugins/rpsystem/managers/ConfigManager.java, src/main/java/dansplugins/rpsystem/managers/StorageManager.java, src/main/java/dansplugins/rpsystem/objects/CharacterCard.java, src/main/java/dansplugins/rpsystem/utils/ColorChecker.java
=> Debug Mode

pom.xml, src/main/java/dansplugins/rpsystem/CommandInterpreter.java, src/main/java/dansplugins/rpsystem/MedievalRoleplayEngine.java, src/main/java/dansplugins/rpsystem/commands/CardCommand.java, src/main/resources/plugin.yml
=> Optimizing the /card command.

src/main/java/dansplugins/rpsystem/CommandInterpreter.java, src/main/java/dansplugins/rpsystem/commands/CardCommand.java, src/main/java/dansplugins/rpsystem/services/CardLookupService.java, src/main/java/dansplugins/rpsystem/services/ICardLookupService.java, src/main/java/dansplugins/rpsystem/utils/Logger.java
=> Card Lookup Service

src/main/java/dansplugins/rpsystem/eventhandlers/InteractionHandler.java
Checks for a false on the NPC meta data
Issue link #206
=> Fixes Issue #206 NPE on Citizen NPC interaction

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, pom.xml, src/main/java/dansplugins/exceptions/MailboxesNotFoundException.java, src/main/java/dansplugins/exceptions/MedievalFactionsNotFoundException.java, src/main/java/dansplugins/rpsystem/MedievalRoleplayEngine.java, src/main/java/dansplugins/rpsystem/Messenger.java, src/main/java/dansplugins/rpsystem/commands/BirdCommand.java, src/main/java/dansplugins/rpsystem/commands/LocalChatCommand.java, src/main/java/dansplugins/rpsystem/eventhandlers/ChatHandler.java, src/main/java/dansplugins/rpsystem/integrators/MailboxesIntegrator.java, src/main/java/dansplugins/rpsystem/integrators/MedievalFactionsIntegrator.java, src/main/resources/plugin.yml
Running into these errors should no longer make the plugin unusable.
=> Fixed MF & Mailboxes integration errors.

src/main/java/dansplugins/rpsystem/commands/HelpCommand.java, src/main/java/dansplugins/rpsystem/commands/SetCommand.java, src/main/java/dansplugins/rpsystem/commands/UnsetCommand.java, src/main/resources/plugin.yml
It's now possible to do a bit of moderating with cards.
=> Setting & Unsetting Fields in Other Players' Cards

src/main/java/dansplugins/rpsystem/commands/BirdCommand.java, src/main/java/dansplugins/rpsystem/commands/GlobalChatCommand.java, src/main/java/dansplugins/rpsystem/listeners/ChatListener.java, src/main/resources/config.yml
=> Changed legacyChat config option to overrideGlobal.

src/main/java/dansplugins/rpsystem/commands/card/CardCommand.java
The changes in this PR make the fields in character cards support spaces, excluding the age field.
closes #279
=> Feature - Support Spaces

src/main/java/dansplugins/rpsystem/commands/card/CardCommand.java
The input for the 'card age' command is now validated.
=> Bug Fix - Validate Age Input

src/main/java/dansplugins/rpsystem/commands/bird/BirdCommand.java, src/main/java/dansplugins/rpsystem/config/ConfigService.java
=> Feature - Configure bird speed
